name: ${{values.app_name}}-CICD

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{'${{ secrets.DOCKER_USERNAME }}'}}
          password: ${{'${{ secrets.DOCKER_PASSWORD }}'}}
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{'${{ secrets.DOCKER_USERNAME }}'}}/${{values.app_name}}:${{'${{ env.SHORT_SHA }}'}}
    outputs:
      short_commit_sha: ${{'${{ env.SHORT_SHA }}'}}
    
  cd: 
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update image tag
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{'${{ needs.ci.outputs.short_commit_sha }}'}}\"/" charts/${{values.app_name}}/values-${{values.app_env}}.yaml
          
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update image tag to ${{'${{ needs.ci.outputs.short_commit_sha }}'}}"
          add: "charts/${{values.app_name}}/values-${{values.app_env}}.yaml"
          push: true

      - name: Install ArgoCD CLI
        run: |
          curl -L -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/
          
      - name: Deploy to ArgoCD
        run: |
          # Login to ArgoCD
          argocd login --insecure --grpc-web argocd-server.argocd-backstage --username admin --password ${{'${{ secrets.ARGOCD_PASSWORD }}'}}

          repo=https://github.com/hexspark-digital/${{values.app_name}}
          
          # Add repository with retry
          for i in {1..3}; do
            if argocd repo add $repo; then
              echo "Repository added successfully"
              break
            else
              echo "Attempt $i failed, retrying in 10 seconds..."
              sleep 10
            fi
          done

          # Check if the application already exists
          if argocd app get ${{values.app_name}} >/dev/null 2>&1; then
            echo "Application already exists, syncing..."
            argocd app sync ${{values.app_name}}
          else
            echo "Creating new application..."
            # Create application with retry
            for i in {1..3}; do
              if argocd app create ${{values.app_name}} \
                --repo $repo \
                --path charts/${{values.app_name}} \
                --dest-namespace ${{values.app_env}} \
                --values charts/${{values.app_name}}/values-${{values.app_env}}.yaml \
                --dest-server https://kubernetes.default.svc \
                --sync-policy auto \
                --revision main \
                --sync-option CreateNamespace=true; then
                echo "Application created successfully"
                break
              else
                echo "Attempt $i failed, retrying in 15 seconds..."
                sleep 15
              fi
            done
          fi

          # Wait for synchronization
          argocd app wait ${{values.app_name}} --timeout 300
            
