name: ${{values.app_name}}-CICD

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{'${{ secrets.DOCKER_USERNAME }}'}}
          password: ${{'${{ secrets.DOCKER_PASSWORD }}'}}
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{'${{ secrets.DOCKER_USERNAME }}'}}/${{values.app_name}}:${{'${{ env.SHORT_SHA }}'}}
    outputs:
      short_commit_sha: ${{'${{ env.SHORT_SHA }}'}}
    
  cd: 
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update image tag
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{'${{ needs.ci.outputs.short_commit_sha }}'}}\"/" charts/${{values.app_name}}/values-${{values.app_env}}.yaml
          
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update image tag to ${{'${{ needs.ci.outputs.short_commit_sha }}'}}"
          add: "charts/${{values.app_name}}/values-${{values.app_env}}.yaml"
          push: true

      - name: Install ArgoCD CLI
        run: |
          curl -L -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/
          
      - name: Deploy to ArgoCD
        run: |
          # Login to ArgoCD
          argocd login --insecure --grpc-web argocd-server.argocd-backstage --username admin --password ${{'${{ secrets.ARGOCD_PASSWORD }}'}}

          repo=https://github.com/hexspark-digital/${{values.app_name}}
          argocd repo list | grep -q $repo || argocd repo add $repo
         
          # Check if the application already exists
          if argocd app get ${{values.app_name}} >/dev/null 2>&1; then
            echo "Application already exists, syncing..."
            argocd app sync ${{values.app_name}}
          else
            echo "Creating new application..."
            argocd app create ${{values.app_name}} \
              --repo $repo \
              --path charts/${{values.app_name}} \
              --dest-namespace ${{values.app_env}} \
              --values values-${{values.app_env}}.yaml \
              --dest-server https://kubernetes.default.svc \
              --sync-policy manual \
              --revision main \
              --sync-option CreateNamespace=true
            echo "Application created successfully"
          fi

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          # Configure kubectl to use the same cluster as ArgoCD
          kubectl config set-cluster default --server=https://kubernetes.default.svc --insecure-skip-tls-verify=true
          kubectl config set-context default --cluster=default --user=default
          kubectl config use-context default

      - name: Debug application status
        shell: bash
        run: |
          argocd login --insecure --grpc-web argocd-server.argocd-backstage --username admin --password ${{'${{ secrets.ARGOCD_PASSWORD }}'}}
          
          echo "=== Application Status ==="
          argocd app get ${{values.app_name}}
          
          echo "=== Pod Status ==="
          kubectl get pods -n ${{values.app_env}} -l app.kubernetes.io/name=${{values.app_name}} || echo "No pods found"
          
          echo "=== Pod Logs ==="
          kubectl logs -n ${{values.app_env}} -l app.kubernetes.io/name=${{values.app_name}} --tail=50 || echo "No logs available yet"
          
          echo "=== Events ==="
          kubectl get events -n ${{values.app_env}} --sort-by='.lastTimestamp' | tail -10 || echo "No events found"
          
          echo "=== Deployment Status ==="
          kubectl get deployment -n ${{values.app_env}} ${{values.app_name}} -o wide || echo "Deployment not found"

      - name: Wait for synchronization
        shell: bash
        run: |
          argocd login --insecure --grpc-web argocd-server.argocd-backstage --username admin --password ${{'${{ secrets.ARGOCD_PASSWORD }}'}}
          argocd app wait ${{values.app_name}} --timeout 600
            
