apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: An example of a API in Node.js.
  annotations:
    github.com/project-slug: felipeneuhauss/${{values.app_name}}
    backstage.io/techdocs-ref: dir:./
spec:
  type: service
  owner: development
  lifecycle: experimental
